//usuario
export const LOGIN = "LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";
export const REGISTRARSE = "REGISTRARSE";
export const GET_ALL_USUARIOS = "GET_ALL_USUARIOS";
export const GET_USUARIOS_BY_ROL = "GET_USUARIOS_BY_ROL";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_DNI = "GET_USER_BY_DNI";
export const RESET_USER = "RESET_USER";
export const MODIFICA_USUARIO = "MODIFICA_USUARIO";
export const LOADING = "LOADING";

//productos
export const GET_PRODUCTOS_REQUEST = "GET_PRODUCTOS_REQUEST";
export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const GET_PRODUCTOS_FAILURE = "GET_PRODUCTOS_FAILURE";
export const GET_PRODUCTOS_ADMIN = "GET_PRODUCTOS_ADMIN";
export const CREATE_PRODUCTO = "CREATE_PRODUCTO";
export const UPDATE_PRODUCTO = "UPDATE_PRODUCTO";
export const DELETE_PRODUCTO = "DELETE_PRODUCTO";

//configuracion sitio
export const GET_CONFIGURACION_SITIO = "GET_CONFIGURACION_SITIO";
export const UPDATE_CONFIGURACION_SITIO = "UPDATE_CONFIGURACION_SITIO";
